import json, os

data_hi = {
  "common": {
    "welcome": "SKLP में आपका स्वागत है",
    "home": "होम",
    "products": "उत्पाद",
    "categories": "श्रेणियाँ",
    "cart": "कार्ट",
    "checkout": "चेकआउट",
    "account": "खाता",
    "wishlist": "विशलिस्ट",
    "orders": "ऑर्डर",
    "myOrders": "मेरे ऑर्डर",
    "myWishlist": "मेरी विशलिस्ट",
    "profile": "प्रोफ़ाइल",
    "settings": "सेटिंग्स",
    "logout": "साइन आउट",
    "login": "साइन इन",
    "register": "साइन अप",
    "search": "खोजें",
    "filter": "फ़िल्टर",
    "sort": "क्रमबद्ध करें",
    "price": "कीमत",
    "rating": "रेटिंग",
    "reviews": "समीक्षाएं",
    "inStock": "स्टॉक में है",
    "outOfStock": "स्टॉक समाप्त",
    "quantity": "मात्रा",
    "addToCart": "कार्ट में जोड़ें",
    "addingToCart": "जोड़ा जा रहा है...",
    "addedToCart": "कार्ट में जोड़ा गया!",
    "buyNow": "अभी खरीदें",
    "addToWishlist": "विशलिस्ट में जोड़ें",
    "addedToWishlist": "विशलिस्ट में जोड़ा गया!",
    "removeFromWishlist": "विशलिस्ट से हटाएं",
    "removedFromWishlist": "विशलिस्ट से हटाया गया",
    "save": "परिवर्तन सहेजें",
    "saving": "सहेजा जा रहा है...",
    "cancel": "रद्द करें",
    "delete": "हटाएं",
    "edit": "संपादित करें",
    "update": "अपडेट करें",
    "updating": "अपडेट हो रहा है...",
    "next": "अगला",
    "previous": "पिछला",
    "back": "वापस",
    "confirm": "पुष्टि करें",
    "close": "बंद करें",
    "loading": "लोड हो रहा है...",
    "error": "त्रुटि",
    "success": "सफलता",
    "warning": "चेतावनी",
    "info": "जानकारी",
    "noResults": "कोई परिणाम नहीं मिला",
    "tryAgain": "पुनः प्रयास करें",
    "viewAll": "सभी देखें",
    "viewDetails": "विवरण देखें",
    "showMore": "और देखें",
    "showLess": "कम देखें",
    "explore": "कलेक्शन देखें",
    "learnMore": "और जानें",
    "submit": "सबमिट करें",
    "apply": "लागू करें",
    "applied": "लागू हुआ",
    "remove": "हटाएं",
    "clear": "साफ़ करें",
    "clearAll": "सभी साफ़ करें",
    "select": "चुनें",
    "selectOption": "एक विकल्प चुनें",
    "optional": "वैकल्पिक",
    "required": "अनिवार्य",
    "all": "सभी",
    "or": "या",
    "and": "और",
    "rs": "₹",
    "discount": "छूट",
    "subtotal": "उप-कुल",
    "total": "कुल",
    "grandTotal": "कुल देय राशि",
    "taxes": "अनुमानित कर",
    "shipping": "डिलीवरी शुल्क",
    "free": "मुफ़्त",
    "freeShipping": "मुफ़्त डिलीवरी",
    "expressDelivery": "एक्सप्रेस डिलीवरी",
    "cashOnDelivery": "कैश ऑन डिलीवरी",
    "upi": "यूपीआई",
    "creditDebitCard": "क्रेडिट / डेबिट कार्ड",
    "clubTier": "क्लब टियर",
    "goldMember": "गोल्ड एलीट",
    "verified": "सत्यापित",
    "active": "सक्रिय",
    "secure": "सुरक्षित",
    "linked": "लिंक किया गया",
    "notLinked": "लिंक नहीं है",
    "default": "डिफ़ॉल्ट",
    "change": "बदलें",
    "add": "जोड़ें",
    "addNew": "नया जोड़ें",
    "item": "वस्तु",
    "items": "वस्तुएं",
    "piece": "पीस",
    "pieces": "पीस",
    "size": "साइज़",
    "color": "रंग",
    "qty": "मात्रा",
    "continueShopping": "खरीदारी जारी रखें",
    "backToHome": "होम पर वापस जाएं",
    "needHelp": "सहायता चाहिए?",
    "chatWithUs": "हमसे चैट करें",
    "callUs": "हेल्पलाइन पर कॉल करें",
    "emailUs": "ईमेल सहायता",
    "copyright": "© 2026 SKLP फैशन। सर्वाधिकार सुरक्षित।"
  },
  "header": {
    "search": "उत्पाद खोजें...",
    "searchPlaceholder": "खूबसूरत कपड़े, साड़ियाँ, जूते खोजें...",
    "cart": "कार्ट",
    "wishlist": "विशलिस्ट",
    "account": "खाता",
    "notifications": "सूचनाएं",
    "darkMode": "डार्क मोड",
    "lightMode": "लाइट मोड",
    "theme": "थीम",
    "language": "भाषा",
    "selectLanguage": "भाषा चुनें",
    "accessClub": "साइन इन",
    "clubProfile": "प्रोफ़ाइल",
    "predictiveAi": "SKLP स्मार्ट सर्च",
    "inputPlaceholder": "सिल्क साड़ियाँ, जूते, शर्ट खोजें...",
    "didYouMean": "क्या आपका मतलब था:",
    "predictiveMatches": "परिणाम",
    "aiRecommended": "अनुशंसित उत्पाद",
    "listening": "सुन रहे हैं...",
    "listeningInstructions": "माइक्रोफ़ोन में स्पष्ट रूप से बोलें। 'साड़ी' या 'ब्लेज़र' कहें।",
    "adminPanel": "एडमिन पैनल",
    "sellerHub": "सेलर हब",
    "deliveryHub": "डिलीवरी हब",
    "profile": "प्रोफ़ाइल",
    "signIn": "साइन इन",
    "signOut": "साइन आउट",
    "myOrders": "मेरे ऑर्डर",
    "myWishlist": "मेरी विशलिस्ट",
    "savedAddresses": "सहेजे गए पते",
    "currency": "मुद्रा",
    "searchTitle": "SKLP फैशन सर्च",
    "trendingSearches": "ट्रेंडिंग सर्च"
  },
  "sidebar": {
    "browseCollections": "कलेक्शन ब्राउज़ करें",
    "shoppingZone": "शॉपिंग ज़ोन",
    "clientServices": "ग्राहक सेवाएं",
    "adminManagement": "एडमिन प्रबंधन",
    "sellerHub": "सेलर हब",
    "deliveryHub": "डिलीवरी हब",
    "mensFashion": "पुरुषों का फैशन",
    "womensFashion": "महिलाओं का फैशन",
    "kidsCorner": "बच्चों के कपड़े",
    "premiumFootwear": "प्रीमियम जूते",
    "luxuryAccessories": "फैशन एक्सेसरीज़",
    "luxuryCollections": "विशिष्ट कलेक्शन",
    "trendingProducts": "ट्रेंडिंग ऑउटफिट्स",
    "newArrivals": "नए आगमन",
    "coutureOffers": "विशेष ऑफ़र",
    "recommendedForYou": "आपके लिए अनुशंसित",
    "myWishlist": "मेरी विशलिस्ट",
    "orderTracking": "ऑर्डर ट्रैकिंग",
    "customerSupport": "ग्राहक सहायता",
    "settings": "सेटिंग्स",
    "accountSettings": "अकाउंट सेटिंग्स",
    "personalDetails": "व्यक्तिगत विवरण",
    "savedAddresses": "सहेजे गए पते",
    "securityPassword": "सुरक्षा एवं पासवर्ड",
    "paymentMethods": "भुगतान विधियाँ एवं यूपीआई",
    "displayRegion": "डिस्प्ले एवं क्षेत्र",
    "notifications": "सूचनाएं",
    "adminDashboard": "एडमिन डैशबोर्ड",
    "manageProducts": "उत्पाद प्रबंधन",
    "manageOrders": "ऑर्डर प्रबंधन",
    "manageUsers": "यूज़र प्रबंधन",
    "analyticsOverview": "एनालिटिक्स अवलोकन",
    "sellerDashboard": "सेलर डैशबोर्ड",
    "myProducts": "मेरे उत्पाद",
    "addNewProduct": "नया उत्पाद जोड़ें",
    "earningsPayouts": "कमाई एवं भुगतान",
    "salesAnalytics": "बिक्री एनालिटिक्स",
    "deliveryDashboard": "डिलीवरी डैशबोर्ड",
    "activeDeliveries": "सक्रिय डिलीवरी",
    "routeMap": "रूट मैप",
    "earningsToday": "आज की कमाई",
    "otpVerification": "ओटीपी सत्यापन",
    "welcomeGuest": "अतिथि का स्वागत है",
    "sklpFashionStore": "SKLP फैशन स्टोर",
    "goToDashboard": "डैशबोर्ड पर जाएं",
    "signOut": "साइन आउट",
    "enterAtelier": "साइन इन",
    "loyaltyClub": "SKLP रिवार्ड्स क्लब",
    "loyaltyClubText": "मुफ़्त तेज़ डिलीवरी, कस्टम फिटिंग और नए त्यौहारी परिधानों तक त्वरित पहुँच का आनंद लें।",
    "eliteTier": "गोल्ड मेंबर"
  },
  "footer": {
    "description": "सभी के लिए प्रीमियम फैशन और जूते। SKLP के साथ लक्ज़री स्टाइल और आराम का अनुभव करें।",
    "quickLinks": "त्वरित लिंक",
    "home": "होम",
    "products": "उत्पाद",
    "aboutUs": "हमारे बारे में",
    "contact": "संपर्क करें",
    "support": "सहायता",
    "shippingInfo": "शिपिंग जानकारी",
    "returns": "रिटर्न",
    "faq": "अक्सर पूछे जाने वाले प्रश्न",
    "trackOrder": "ऑर्डर ट्रैक करें",
    "newsletter": "न्यूज़लेटर",
    "newsletterText": "विशेष ऑफ़र और नए कलेक्शन के अपडेट पाने के लिए सब्सक्राइब करें।",
    "emailPlaceholder": "अपना ईमेल दर्ज करें",
    "join": "सब्सक्राइब",
    "allRightsReserved": "© 2026 SKLP फैशन। सर्वाधिकार सुरक्षित।",
    "privacyPolicy": "गोपनीयता नीति",
    "termsOfService": "सेवा की शर्तें",
    "cookiePolicy": "कुकी नीति",
    "shippingPolicy": "शिपिंग नीति",
    "returnsRefunds": "रिटर्न एवं रिफंड",
    "paymentSecurity": "भुगतान सुरक्षा",
    "vipPlan": "वीआईपी सदस्यता",
    "chatBot": "एआई चैटबॉट",
    "helplineInfo": "हेल्पलाइन एवं जानकारी",
    "customerCare": "कस्टमर केयर",
    "callHelpline": "+91 9948682179 (सोम-शनि, सुबह 9 - रात 8)",
    "emailSupport": "support@sklp.com",
    "storeAddress": "SKLP लक्ज़री टावर, जुबली हिल्स, हैदराबाद, भारत"
  },
  "home": {
    "hero": "सुंदर फैशन की खोज करें",
    "heroSubtitle": "हस्तनिर्मित भारतीय परिधान और समकालीन लक्ज़री स्टाइल",
    "heroCta": "कलेक्शन देखें",
    "featured": "विशेष उत्पाद",
    "trending": "अभी ट्रेंड में",
    "collections": "विशिष्ट कलेक्शन",
    "banner": "विशेष ऑफ़र",
    "interactiveCatalog": "सभी उत्पाद",
    "eliteLabels": "शीर्ष ब्रांड पार्टनर",
    "conciergeServices": "प्रीमियम सेवाएं",
    "curatedRecs": "आपके लिए अनुशंसित",
    "curatedRecsDesc": "आपके लिए विशेष रूप से चुने गए खूबसूरत और सुरुचिपूर्ण कपड़ों की खोज करें।",
    "styleEngineDesc": "आपकी पसंद के अनुसार सटीक मेल खाते परिधान।",
    "aiSmartPicks": "एआई स्टाइल सुझाव",
    "hotReleases": "नई रिलीज़",
    "hotReleasesDesc": "हमारे चुनिंदा ट्रेंडिंग फैशन उत्पादों को देखें।",
    "categoriesDesc": "सुंदर कलेक्शन देखने के लिए श्रेणियां चुनें।",
    "shopByCouture": "श्रेणी के अनुसार खरीदारी करें",
    "onlyLeft": "स्टॉक में केवल {{count}} बचे हैं",
    "viewCollection": "कलेक्शन देखें",
    "shopNow": "अभी खरीदें",
    "newSeason": "नया सीज़न 2026",
    "festiveSpecial": "त्यौहारी स्पेशल",
    "royalHeritage": "शाही विरासत",
    "limitedEdition": "सीमित संस्करण",
    "customerReviews": "ग्राहकों के अनुभव",
    "trustedBy": "भारत भर में 50,000+ से अधिक लक्ज़री फैशन प्रेमियों का भरोसा",
    "freeDeliveryBadge": "मुफ़्त बीमाकृत डिलीवरी",
    "securePaymentsBadge": "100% सुरक्षित भुगतान",
    "easyReturnsBadge": "7-दिवसीय आसान रिटर्न",
    "luxuryCareBadge": "24/7 ग्राहक सहायता",
    "slide1": {
      "title": "द रेनेसांस\nऑफ़ कोट्यूर",
      "subtitle": "विशेष कलेक्शन 2026",
      "desc": "सोने के तारों से बुनी गई शुद्ध बनारसी सिल्क और प्रीमियम साटन फ़िनिश।",
      "cta": "खोजें"
    },
    "slide2": {
      "title": "सिल्हूट्स\nइन वेलवेट",
      "subtitle": "प्रीमियम पुरुषों के परिधान",
      "desc": "शाम के आयोजनों के लिए तैयार किए गए आकर्षक ब्लेज़र और टेलर्ड कोट।",
      "cta": "वेलवेट देखें"
    },
    "slide3": {
      "title": "किड्स लक्स\nएडिट",
      "subtitle": "बच्चों के प्यारे डंगरी परिधान",
      "desc": "विशेष डेनिम ओवरऑल और आरामदायक लेदर स्नीकर्स।",
      "cta": "बच्चों के कपड़े"
    },
    "service1": {
      "title": "मुफ़्त डिलीवरी",
      "desc": "₹1,999 से अधिक के ऑर्डर पर"
    },
    "service2": {
      "title": "प्रामाणिक लक्ज़री",
      "desc": "100% असली व उच्च गुणवत्ता वाले उत्पाद"
    },
    "service3": {
      "title": "आसान रिटर्न",
      "desc": "7 दिनों की आसान वापसी और फिटिंग"
    },
    "service4": {
      "title": "स्टाइलिंग सहायता",
      "desc": "24/7 समर्पित ग्राहक सहायता"
    },
    "brand1": {
      "desc": "उत्कृष्ट सिल्क बुनाई और हस्तशिल्प"
    },
    "brand2": {
      "desc": "गहरे वेलवेट इवनिंग वियर और ब्लेज़र"
    },
    "brand3": {
      "desc": "गोल्ड टच के साथ आधुनिक स्पोर्ट्स वियर"
    },
    "brand4": {
      "desc": "इटैलियन लेदर बूट्स और आभूषण"
    }
  },
  "products": {
    "title": "हमारे कलेक्शन",
    "subtitle": "उच्च फैशन परिधान, पारंपरिक वस्त्र और लक्ज़री जूतों का अन्वेषण करें।",
    "description": "विशिष्ट शैली के व्यक्तियों के लिए तैयार किए गए डिज़ाइनर परिधान और प्रीमियम इटैलियन लेदर फुटवियर।",
    "categories": "श्रेणियाँ",
    "allProducts": "सभी उत्पाद",
    "men": "पुरुष",
    "women": "महिलाएं",
    "kids": "बच्चे",
    "clothing": "कपड़े",
    "footwear": "जूते",
    "accessories": "एक्सेसरीज़",
    "resetFilters": "फ़िल्टर रीसेट करें",
    "searchPlaceholder": "फैशन परिधान, साड़ियाँ, वेलवेट कपड़े खोजें...",
    "aiSuggestions": "एआई स्मार्ट सुझाव",
    "newestFirst": "नवीनतम पहले",
    "priceLowHigh": "कीमत: कम से अधिक",
    "priceHighLow": "कीमत: अधिक से कम",
    "topRated": "सर्वोच्च रेटेड",
    "refineBy": "फ़िल्टर विकल्प",
    "gender": "लिंग",
    "allGenders": "सभी के लिए",
    "category": "श्रेणी",
    "allCategories": "सभी श्रेणियां",
    "priceLimit": "मूल्य सीमा",
    "priceRange": "मूल्य दायरा",
    "noMatches": "आपके फ़िल्टर से मेल खाता कोई उत्पाद नहीं मिला।",
    "noMatchesDesc": "कृपया अन्य खोज शब्द या फ़िल्टर आज़माएं।",
    "showAll": "सभी उत्पाद दिखाएं",
    "filters": "फ़िल्टर",
    "clearAll": "सभी साफ़ करें",
    "applyFilters": "फ़िल्टर लागू करें",
    "itemsFound": "{{count}} उत्पाद मिले",
    "sortBy": "क्रमबद्ध करें",
    "popular": "सर्वाधिक लोकप्रिय",
    "discountHighLow": "छूट: अधिक से कम"
  },
  "productDetail": {
    "addToCart": "कार्ट में जोड़ें",
    "buyNow": "अभी खरीदें",
    "adding": "जोड़ा जा रहा है...",
    "outOfStock": "वर्तमान में अनुपलब्ध",
    "selectSize": "साइज़ चुनें",
    "selectColor": "रंग चुनें",
    "sizeGuide": "साइज़ गाइड",
    "deliveryOptions": "डिलीवरी विकल्प",
    "checkPincode": "पिनकोड जांचें",
    "check": "जांचें",
    "enterPincode": "6 अंकों का पिनकोड दर्ज करें",
    "freeDeliveryAvailable": "इस वस्तु पर मुफ़्त डिलीवरी उपलब्ध है",
    "codAvailable": "कैश ऑन डिलीवरी उपलब्ध है",
    "easyReturns": "7 दिनों का आसान रिटर्न और एक्सचेंज",
    "authenticProduct": "100% प्रामाणिक एवं गुणवत्ता आश्वासित",
    "productDetails": "उत्पाद विवरण एवं विनिर्देश",
    "fabricCare": "फ़ैब्रिक एवं देखभाल निर्देश",
    "reviews": "ग्राहक समीक्षाएं",
    "ratingOverview": "रेटिंग अवलोकन",
    "verifiedBuyer": "सत्यापित खरीदार",
    "writeReview": "समीक्षा लिखें",
    "relatedProducts": "आपको ये भी पसंद आ सकते हैं",
    "completeTheLook": "इस लुक को पूरा करें",
    "shareProduct": "शेयर करें",
    "selectSizeAlert": "कार्ट में जोड़ने से पहले कृपया साइज़ चुनें",
    "addedSuccessToast": "उत्पाद कार्ट में सफलतापूर्वक जोड़ा गया!",
    "inStockBadge": "स्टॉक में है - डिलीवरी के लिए तैयार",
    "hurryLeft": "जल्दी करें, केवल {{count}} बचे हैं!"
  },
  "cart": {
    "title": "शॉपिंग कार्ट",
    "empty": "आपकी कार्ट खाली है",
    "emptyDesc": "हमारे कलेक्शन को एक्सप्लोर करें और SKLP के प्रीमियम फैशन का अनुभव करें।",
    "startShopping": "खरीदारी शुरू करें",
    "continueShopping": "खरीदारी जारी रखें",
    "subtotal": "उप-कुल",
    "shipping": "डिलीवरी",
    "tax": "कर",
    "total": "कुल",
    "discount": "छूट",
    "grandTotal": "कुल देय राशि",
    "proceed": "सुरक्षित चेकआउट पर जाएं",
    "proceedCheckout": "चेकआउट पर जाएं",
    "qualifyFreeShipping": "बधाई हो! आप मुफ़्त बीमाकृत डिलीवरी के पात्र हैं",
    "addMoreFreeShipping": "मुफ़्त एक्सप्रेस डिलीवरी के लिए ₹{{amount}} और जोड़ें",
    "clearCart": "कार्ट खाली करें",
    "clearConfirm": "क्या आप वाकई अपनी कार्ट खाली करना चाहते हैं?",
    "promoCoupon": "प्रोमो कूपन",
    "couponPlaceholder": "कूपन कोड दर्ज करें (उदा. SKLP20)",
    "viewCoupons": "उपलब्ध कूपन देखें",
    "apply": "लागू करें",
    "applied": "लागू हुआ",
    "remove": "हटाएं",
    "orderSummary": "ऑर्डर सारांश",
    "shippingCharges": "डिलीवरी शुल्क",
    "estimatedTaxes": "अनुमानित कर",
    "storeCoupons": "स्टोर कूपन",
    "saveExtra": "कूपन कोड के साथ अतिरिक्त बचत करें",
    "freeInsuredShipping": "मुफ़्त बीमाकृत डिलीवरी",
    "secureCheckoutBadge": "100% सुरक्षित चेकआउट गारंटी",
    "itemsInCart": "कार्ट में {{count}} वस्तुएं",
    "itemRemoved": "वस्तु कार्ट से हटा दी गई",
    "cartCleared": "कार्ट सफलतापूर्वक खाली कर दी गई",
    "couponApplied": "कूपन {{code}} सफलतापूर्वक लागू हुआ!",
    "couponRemoved": "कूपन हटा दिया गया",
    "invalidCoupon": "अमान्य या समाप्त कूपन कोड"
  },
  "checkout": {
    "title": "सुरक्षित चेकआउट",
    "logInToSecure": "चेकआउट के लिए साइन इन करें",
    "noAccountDesc": "सुरक्षित भुगतान गेटवे तक पहुँचने के लिए कृपया साइन इन करें या रजिस्टर करें।",
    "contactInfo": "1. संपर्क जानकारी",
    "deliveryAddress": "2. डिलीवरी का पता",
    "selectAddress": "डिलीवरी का पता चुनें",
    "addNewAddress": "नया पता जोड़ें",
    "paymentDetails": "3. भुगतान विधि",
    "orderReview": "ऑर्डर समीक्षा",
    "insuredShipping": "बीमाकृत एक्सप्रेस डिलीवरी",
    "placeOrder": "ऑर्डर दें",
    "placingOrder": "ऑर्डर प्रोसेस हो रहा है...",
    "orderSuccess": "ऑर्डर सफलतापूर्वक दिया गया!",
    "orderFailed": "ऑर्डर असफल रहा",
    "streetAddress": "मकान नं. / सड़क का पता",
    "city": "शहर",
    "state": "राज्य",
    "postalCode": "पिन कोड",
    "country": "देश",
    "landmark": "लैंडमार्क (वैकल्पिक)",
    "phone": "मोबाइल नंबर",
    "name": "पूरा नाम",
    "cod": "कैश ऑन डिलीवरी (COD)",
    "codDesc": "अपने घर पर पार्सल प्राप्त करते समय नकद या यूपीआई द्वारा भुगतान करें।",
    "card": "क्रेडिट / डेबिट कार्ड",
    "cardDesc": "वीज़ा, मास्टरकार्ड, रुपे कार्ड 256-बिट एन्क्रिप्शन के साथ सुरक्षित।",
    "upi": "यूपीआई (Google Pay, PhonePe, Paytm, BHIM)",
    "upiDesc": "अपने पसंदीदा यूपीआई ऐप द्वारा 1-क्लिक में त्वरित भुगतान।",
    "razorpay": "रेज़रपे सुरक्षित गेटवे",
    "razorpayDesc": "नेट बैंकिंग, कार्ड, वॉलेट या यूपीआई द्वारा सुरक्षित भुगतान करें।",
    "selectPaymentMethod": "कृपया भुगतान विधि चुनें",
    "orderSummary": "ऑर्डर सारांश",
    "itemsCount": "{{count}} वस्तु(एं)",
    "itemTotal": "वस्तुओं का कुल मूल्य",
    "deliveryFee": "डिलीवरी शुल्क",
    "couponDiscount": "कूपन छूट",
    "finalAmount": "अंतिम देय राशि",
    "agreeTerms": "यह ऑर्डर देकर आप SKLP सेवा शर्तों और गोपनीयता नीति से सहमत होते हैं।",
    "addressRequired": "कृपया वैध डिलीवरी पता चुनें",
    "paymentMethodRequired": "कृपया भुगतान विकल्प चुनें"
  },
  "orders": {
    "title": "मेरे ऑर्डर",
    "myOrders": "ऑर्डर इतिहास",
    "subtitle": "लाइव शिपमेंट ट्रैक करें, पिछली खरीदारी देखें और इनवॉइस डाउनलोड करें।",
    "trackOrder": "शिपमेंट ट्रैक करें",
    "orderId": "ऑर्डर आईडी",
    "orderDate": "ऑर्डर तिथि",
    "orderStatus": "ऑर्डर स्थिति",
    "paymentStatus": "भुगतान स्थिति",
    "totalAmount": "कुल राशि",
    "items": "ऑर्डर की गई वस्तुएं",
    "viewDetails": "विवरण देखें",
    "cancelOrder": "ऑर्डर रद्द करें",
    "reorder": "पुनः ऑर्डर करें",
    "invoice": "टैक्स इनवॉइस",
    "downloadInvoice": "इनवॉइस डाउनलोड करें",
    "trackShipment": "लाइव डिलीवरी ट्रैक करें",
    "shippingAddress": "डिलीवरी का पता",
    "paymentMethod": "भुगतान विधि",
    "estimatedDelivery": "अनुमानित डिलीवरी तिथि",
    "trackingTimeline": "डिलीवरी टाइमलाइन",
    "noOrders": "अभी तक कोई ऑर्डर नहीं",
    "noOrdersDesc": "आपने अभी तक कोई ऑर्डर नहीं दिया है। हमारे नवीनतम कलेक्शन देखें और खरीदारी शुरू करें!",
    "startShoppingNow": "अभी खरीदारी शुरू करें",
    "cancelConfirm": "क्या आप वाकई इस ऑर्डर को रद्द करना चाहते हैं?",
    "cancelledSuccess": "ऑर्डर सफलतापूर्वक रद्द कर दिया गया",
    "status": {
      "pending": "लंबित है",
      "confirmed": "पुष्टि की गई",
      "processing": "प्रक्रिया में है",
      "shipped": "भेज दिया गया",
      "outForDelivery": "डिलीवरी के लिए निकल चुका है",
      "delivered": "डिलीवर हो गया",
      "cancelled": "रद्द किया गया"
    },
    "payment": {
      "paid": "भुगतान हो गया",
      "pending": "लंबित है",
      "failed": "असफल रहा",
      "refunded": "रिफंड किया गया",
      "cod": "कैश ऑन डिलीवरी"
    }
  },
  "orderTracking": {
    "title": "लाइव ऑर्डर ट्रैकिंग",
    "trackingId": "ट्रैकिंग आईडी",
    "liveStatus": "वर्तमान स्थिति",
    "currentStep": "चरण {{step}} / 4",
    "shipmentDetails": "शिपमेंट विवरण",
    "courierPartner": "कूरियर पार्टनर",
    "trackingNumber": "AWB नंबर",
    "expectedDelivery": "अपेक्षित डिलीवरी तिथि",
    "orderPlaced": "ऑर्डर दिया गया",
    "orderConfirmed": "ऑर्डर की पुष्टि हुई",
    "orderShipped": "फ़ैक्टरी से रवाना हुआ",
    "outForDelivery": "डिलीवरी के लिए निकला",
    "orderDelivered": "सफलतापूर्वक डिलीवर हुआ",
    "needHelpWithOrder": "क्या आपको डिलीवरी में सहायता चाहिए?",
    "contactSupport": "ग्राहक सहायता से संपर्क करें"
  },
  "wishlist": {
    "title": "मेरी विशलिस्ट",
    "subtitle": "सहेजे गए लक्ज़री परिधान और विशेष कलेक्शन।",
    "empty": "आपकी विशलिस्ट खाली है",
    "emptyDesc": "आपने अभी तक कोई वस्तु नहीं सहेजी है। उत्पाद ब्राउज़ करें और दिल के निशान पर टैप करके सहेजें।",
    "exploreCouture": "कलेक्शन देखें",
    "moveToCart": "कार्ट में डालें",
    "removeFromWishlist": "हटाएं",
    "inStock": "स्टॉक में है",
    "outOfStock": "स्टॉक समाप्त",
    "itemsCount": "विशलिस्ट में {{count}} वस्तुएं",
    "clearWishlist": "विशलिस्ट साफ़ करें",
    "itemMovedToCart": "वस्तु सफलतापूर्वक कार्ट में डाली गई!",
    "itemRemoved": "वस्तु विशलिस्ट से हटा दी गई"
  },
  "profile": {
    "title": "अकाउंट सेटिंग्स",
    "subtitle": "अपने व्यक्तिगत विवरण, पते, सुरक्षा और वैश्विक प्राथमिकताएं प्रबंधित करें।",
    "personalDetails": "व्यक्तिगत विवरण",
    "savedAddresses": "सहेजे गए पते",
    "securityPassword": "सुरक्षा एवं पासवर्ड",
    "paymentMethods": "भुगतान विधियाँ एवं यूपीआई",
    "displayRegion": "डिस्प्ले एवं क्षेत्र",
    "notifications": "सूचनाएं",
    "personalInfo": "व्यक्तिगत पहचान",
    "firstName": "पहला नाम",
    "lastName": "अंतिम नाम",
    "email": "ईमेल पता",
    "phone": "मोबाइल नंबर",
    "bio": "बायो / स्टाइल नोट्स",
    "about": "के बारे में",
    "changeAvatar": "अवतार बदलें",
    "saveProfile": "प्रोफ़ाइल परिवर्तन सहेजें",
    "saving": "सहेजा जा रहा है...",
    "profileSaved": "प्रोफ़ाइल विवरण सफलतापूर्वक अपडेट किया गया!",
    "contactInfo": "संपर्क जानकारी",
    "primaryEmail": "प्राथमिक ईमेल",
    "mobileNumber": "मोबाइल नंबर",
    "changeMobile": "बदलें",
    "addMobile": "मोबाइल जोड़ें",
    "sendOtp": "ओटीपी भेजें",
    "verifyOtp": "ओटीपी सत्यापित करें",
    "enterOtp": "6 अंकों का ओटीपी दर्ज करें",
    "otpSent": "आपके नंबर पर ओटीपी सफलतापूर्वक भेजा गया",
    "phoneLinked": "मोबाइल नंबर सफलतापूर्वक लिंक हुआ!",
    "quickActions": "त्वरित क्रियाएं एवं महत्वपूर्ण लिंक",
    "myOrders": "मेरे ऑर्डर",
    "myWishlist": "मेरी विशलिस्ट",
    "becomeSeller": "SKLP सेलर बनें",
    "addressType": "पते का प्रकार",
    "home": "घर",
    "work": "कार्यालय",
    "other": "अन्य",
    "street": "मकान नं. / सड़क का पता",
    "landmark": "लैंडमार्क (वैकल्पिक)",
    "city": "शहर",
    "state": "राज्य",
    "pincode": "पिन कोड",
    "contactPhone": "फोन नंबर",
    "setDefaultAddress": "डिफ़ॉल्ट डिलीवरी पता बनाएं",
    "defaultBadge": "डिफ़ॉल्ट",
    "editAddress": "पता संपादित करें",
    "deleteAddress": "पता हटाएं",
    "addAddress": "डिलीवरी का पता जोड़ें",
    "newAddress": "नया पता जोड़ें",
    "noAddresses": "कोई पता सहेजा नहीं गया है",
    "noAddressesDesc": "त्वरित 1-क्लिक चेकआउट के लिए घर या कार्यालय का पता सहेजें।",
    "addFirstAddress": "अपना पहला पता जोड़ें",
    "addressSaved": "पता सफलतापूर्वक सहेजा गया!",
    "addressDeleted": "पता हटा दिया गया",
    "currentPassword": "वर्तमान पासवर्ड",
    "newPassword": "नया पासवर्ड (कम से कम 8 अक्षर)",
    "confirmPassword": "नए पासवर्ड की पुष्टि करें",
    "updatePassword": "पासवर्ड अपडेट करें",
    "passwordUpdated": "पासवर्ड सफलतापूर्वक अपडेट किया गया!",
    "passwordMismatch": "पासवर्ड मेल नहीं खाते",
    "minPasswordLength": "नया पासवर्ड कम से कम 8 अक्षर का होना चाहिए",
    "accountSecurity": "खाता सुरक्षा",
    "accountStatus": "खाता स्थिति",
    "loginMethod": "लॉगिन विधि",
    "sessionEncrypted": "आपका सत्र 256-बिट एसएसएल सुरक्षा से एन्क्रिप्टेड है।",
    "visualTheme": "विजुअल थीम एवं कंट्रास्ट",
    "darkMode": "डार्क मोड अनुभव",
    "lightMode": "लाइट मोड अनुभव",
    "darkModeDesc": "गोल्ड एक्सेंट के साथ लक्ज़री ब्लैक बैकग्राउंड",
    "displayLanguage": "प्रदर्शन भाषा",
    "preferredCurrency": "पसंदीदा मुद्रा",
    "courierPreferences": "डिफ़ॉल्ट कूरियर प्राथमिकताएं",
    "preferredSlot": "पसंदीदा डिलीवरी समय",
    "slotAnytime": "कार्य समय में कभी भी (सुबह 9 - रात 8)",
    "slotMorning": "सुबह का समय (सुबह 9 - दोपहर 1)",
    "slotAfternoon": "दोपहर का समय (दोपहर 1 - शाम 5)",
    "slotEvening": "शाम का समय (शाम 5 - रात 8)",
    "deliveryInstructions": "विशेष डिलीवरी निर्देश",
    "deliveryInstructionsPlaceholder": "उदा. डिलीवरी से पहले कॉल करें, सुरक्षा गार्ड के पास दें...",
    "savePreferences": "प्राथमिकताएं सहेजें",
    "preferencesSaved": "प्राथमिकताएं सफलतापूर्वक सहेजी गईं!",
    "notificationAlerts": "सूचनाएं एवं संचार अलर्ट",
    "notificationDesc": "ऑर्डर अपडेट और नए कलेक्शन के लिए अपने पसंदीदा चैनल चुनें।",
    "orderAlerts": "लाइव ऑर्डर ट्रैकिंग एवं डिस्पैच अलर्ट",
    "whatsappAlerts": "व्हाट्सएप द्वारा अपडेट",
    "promoAlerts": "विशेष ऑफ़र एवं फेस्टिव कलेक्शन",
    "priceAlerts": "विशलिस्ट मूल्य गिरावट अलर्ट",
    "emailDigest": "ईमेल इनवॉइस एवं मासिक सारांश",
    "saveNotifications": "सूचना प्राथमिकताएं सहेजें",
    "savedUpi": "सहेजे गए यूपीआई आईडी",
    "addUpi": "यूपीआई आईडी जोड़ें",
    "upiId": "यूपीआई आईडी (उदा. name@okhdfcbank)",
    "upiLabel": "लेबल (उदा. Google Pay, PhonePe)",
    "upiSaved": "यूपीआई आईडी सहेजी गई!",
    "upiDeleted": "यूपीआई आईडी हटाई गई",
    "noUpi": "अभी तक कोई यूपीआई आईडी सहेजी नहीं गई है।",
    "atelierWallet": "SKLP वॉलेट",
    "rewardCoins": "उपलब्ध रिवॉर्ड कॉइन्स",
    "coinsWorth": "आपकी अगली खरीदारी पर ₹500 की छूट",
    "coinsDesc": "सभी लक्ज़री ऑर्डर पर 5% कैशबैक पाएं, चेकआउट पर स्वतः लागू होगा।",
    "shopEarn": "खरीदारी करें और रिवॉर्ड्स कमाएं"
  },
  "auth": {
    "login": "साइन इन",
    "register": "खाता बनाएं",
    "signIn": "SKLP में साइन इन करें",
    "signUp": "SKLP से जुड़ें",
    "createAccount": "खाता बनाएं",
    "email": "ईमेल पता",
    "password": "पासवर्ड",
    "confirmPassword": "पासवर्ड की पुष्टि करें",
    "firstName": "पहला नाम",
    "lastName": "अंतिम नाम",
    "phone": "मोबाइल नंबर (10 अंक)",
    "forgotPassword": "पासवर्ड भूल गए?",
    "forgotPasswordDesc": "पासवर्ड रीसेट लिंक प्राप्त करने के लिए अपना पंजीकृत ईमेल दर्ज करें।",
    "resetPassword": "पासवर्ड रीसेट करें",
    "resetPasswordDesc": "अपने खाते को सुरक्षित करने के लिए नया पासवर्ड दर्ज करें।",
    "sendResetLink": "रीसेट लिंक भेजें",
    "resetLinkSent": "पासवर्ड रीसेट लिंक आपके ईमेल पर भेज दिया गया है!",
    "enterNewPassword": "नया पासवर्ड दर्ज करें",
    "updatePassword": "नया पासवर्ड सेट करें",
    "noAccount": "खाता नहीं है?",
    "haveAccount": "पहले से खाता है?",
    "googleLogin": "Google के साथ जारी रखें",
    "googleSignIn": "Google से साइन इन करें",
    "continueWithGoogle": "Google के साथ जारी रखें",
    "orContinueWith": "या ईमेल के साथ जारी रखें",
    "rememberMe": "मुझे साइन इन रखें",
    "agreeToTerms": "मैं SKLP सेवा की शर्तों और गोपनीयता नीति से सहमत हूँ",
    "loginSuccess": "सफलतापूर्वक साइन इन किया गया!",
    "signupSuccess": "खाता सफलतापूर्वक बनाया गया! SKLP में आपका स्वागत है।",
    "logoutSuccess": "सफलतापूर्वक साइन आउट किया गया",
    "invalidCredentials": "अमान्य ईमेल या पासवर्ड। कृपया विवरण जांचें।",
    "emailRequired": "कृपया अपना ईमेल पता दर्ज करें",
    "passwordRequired": "कृपया अपना पासवर्ड दर्ज करें",
    "passwordsMustMatch": "पासवर्ड मेल नहीं खाते",
    "backToLogin": "साइन इन पर वापस जाएं",
    "verifyEmailTitle": "अपना ईमेल सत्यापित करें",
    "verifyEmailDesc": "हमने आपके ईमेल पते पर एक सत्यापन लिंक भेजा है।",
    "resendEmail": "सत्यापन ईमेल पुनः भेजें",
    "emailVerifiedSuccess": "ईमेल सफलतापूर्वक सत्यापित हुआ!"
  },
  "errors": {
    "required": "यह फ़ील्ड अनिवार्य है",
    "invalidEmail": "कृपया एक वैध ईमेल पता दर्ज करें",
    "invalidPhone": "कृपया 10 अंकों का वैध भारतीय मोबाइल नंबर दर्ज करें",
    "passwordMismatch": "पासवर्ड मेल नहीं खाते",
    "minPassword": "पासवर्ड कम से कम 8 अक्षर का होना चाहिए",
    "serverError": "सर्वर त्रुटि हुई। कृपया थोड़ी देर बाद पुनः प्रयास करें।",
    "notFound": "पेज नहीं मिला (404)",
    "notFoundDesc": "आप जो पेज खोज रहे हैं वह मौजूद नहीं है या हटा दिया गया है।",
    "goHome": "होम पर वापस जाएं",
    "somethingWentWrong": "कुछ गलत हो गया। कृपया पेज को रीफ्रेश करें।",
    "tryAgain": "पुनः प्रयास करें",
    "unauthorized": "इस पेज को देखने के लिए कृपया साइन इन करें।",
    "sessionExpired": "आपका सत्र समाप्त हो गया है। कृपया पुनः साइन इन करें।",
    "networkError": "नेटवर्क त्रुटि। कृपया अपना इंटरनेट कनेक्शन जांचें।",
    "formErrors": "कृपया हाइलाइट की गई त्रुटियों को सुधारें।"
  }
}

target_dir = r"c:\mern stack\mernpro\Sklp_ecommers\frontend\src\i18n\locales"
with open(os.path.join(target_dir, "hi.json"), "w", encoding="utf-8") as f:
    json.dump(data_hi, f, ensure_ascii=False, indent=2)

print("hi.json generated successfully")
